const movieList = [
  {
    Title: 'Batman',
    Year: '1989',
    Rated: 'PG-13',
    Released: '23 Jun 1989',
    Runtime: '126 min',
    Genre: 'Action, Adventure',
    Director: 'Tim Burton',
    Writer: 'Bob Kane, Sam Hamm, Warren Skaaren',
    Actors: 'Michael Keaton, Jack Nicholson, Kim Basinger',
    Plot: 'The Dark Knight of Gotham City begins his war on crime with his first major enemy being Jack Napier, a criminal who becomes the clownishly homicidal Joker.',
    Language: 'English, French, Spanish',
    Country: 'United States, United Kingdom',
    Awards: 'Won 1 Oscar. 9 wins & 26 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BZTM2NmZlOTEtYTI5NS00N2JjLWJkNzItMmZkNDBlYmQzNDA2XkEyXkFqcGdeQXVyMTAxODYyODI@._V1_SX300.jpg',
    Ratings: [
      {
        Source: 'Internet Movie Database',
        Value: '7.5/10',
      },
      { Source: 'Rotten Tomatoes', Value: '72%' },
      { Source: 'Metacritic', Value: '69/100' },
    ],
    Metascore: '69',
    imdbRating: '7.5',
    imdbVotes: '372,332',
    imdbID: 'tt0096895',
    Type: 'movie',
    DVD: '22 Aug 1997',
    BoxOffice: '$251,409,241',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Spiderman',
    Year: '1990',
    Rated: 'N/A',
    Released: 'N/A',
    Runtime: '5 min',
    Genre: 'Short',
    Director: 'Christian Davi',
    Writer: 'N/A',
    Actors: 'N/A',
    Plot: 'N/A',
    Language: 'German',
    Country: 'Switzerland',
    Awards: 'N/A',
    Poster: 'N/A',
    Ratings: [
      {
        Source: 'Internet Movie Database',
        Value: '5.6/10',
      },
    ],
    Metascore: 'N/A',
    imdbRating: '5.6',
    imdbVotes: '96',
    imdbID: 'tt0100669',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Iron Man',
    Year: '2008',
    Rated: 'PG-13',
    Released: '02 May 2008',
    Runtime: '126 min',
    Genre: 'Action, Adventure, Sci-Fi',
    Director: 'Jon Favreau',
    Writer: 'Mark Fergus, Hawk Ostby, Art Marcum',
    Actors:
      'Robert Downey Jr., Gwyneth Paltrow, Terrence Howard',
    Plot: 'After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.',
    Language:
      'English, Persian, Urdu, Arabic, Kurdish, Hindi, Hungarian',
    Country: 'United States, Canada',
    Awards:
      'Nominated for 2 Oscars. 21 wins & 73 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_SX300.jpg',
    Ratings: [
      {
        Source: 'Internet Movie Database',
        Value: '7.9/10',
      },
      { Source: 'Rotten Tomatoes', Value: '94%' },
      { Source: 'Metacritic', Value: '79/100' },
    ],
    Metascore: '79',
    imdbRating: '7.9',
    imdbVotes: '1,033,200',
    imdbID: 'tt0371746',
    Type: 'movie',
    DVD: '30 Sep 2008',
    BoxOffice: '$319,034,126',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Pirates',
    Year: '1986',
    Rated: 'PG-13',
    Released: '18 Jul 1986',
    Runtime: '121 min',
    Genre: 'Action, Adventure, Comedy',
    Director: 'Roman Polanski',
    Writer: 'John Brownjohn, Gérard Brach, Roman Polanski',
    Actors: 'Walter Matthau, Cris Campion, Damien Thomas',
    Plot: 'The adventures of pirate Captain Red and his first mate Frog.',
    Language: 'English, French, Spanish',
    Country: 'France, Tunisia',
    Awards:
      'Nominated for 1 Oscar. 2 wins & 2 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNzBmNWNkYTAtYTNhZi00ZjAxLTkzNGQtODk1OTkwZDRmMTJmL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg',
    Ratings: [
      {
        Source: 'Internet Movie Database',
        Value: '6.0/10',
      },
      { Source: 'Rotten Tomatoes', Value: '27%' },
      { Source: 'Metacritic', Value: '32/100' },
    ],
    Metascore: '32',
    imdbRating: '6.0',
    imdbVotes: '8,654',
    imdbID: 'tt0091757',
    Type: 'movie',
    DVD: '21 Aug 2020',
    BoxOffice: '$1,641,825',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Venom',
    Year: '2018',
    Rated: 'PG-13',
    Released: '05 Oct 2018',
    Runtime: '112 min',
    Genre: 'Action, Adventure, Sci-Fi',
    Director: 'Ruben Fleischer',
    Writer: 'Jeff Pinkner, Scott Rosenberg, Kelly Marcel',
    Actors: 'Tom Hardy, Michelle Williams, Riz Ahmed',
    Plot: 'A failed reporter is bonded to an alien entity, one of many symbiotes who have invaded Earth. But the being takes a liking to Earth and decides to protect it.',
    Language: 'English, Mandarin, Malay',
    Country: 'United States, China',
    Awards: '3 wins & 9 nominations',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNTFkZjdjN2QtOGE5MS00ZTgzLTgxZjAtYzkyZWQ5MjEzYmZjXkEyXkFqcGdeQXVyMTM0NTUzNDIy._V1_SX300.jpg',
    Ratings: [
      {
        Source: 'Internet Movie Database',
        Value: '6.6/10',
      },
      { Source: 'Rotten Tomatoes', Value: '30%' },
      { Source: 'Metacritic', Value: '35/100' },
    ],
    Metascore: '35',
    imdbRating: '6.6',
    imdbVotes: '469,857',
    imdbID: 'tt1270797',
    Type: 'movie',
    DVD: '18 Jun 2019',
    BoxOffice: '$213,515,506',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
];

export default movieList;
